<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class ProyectosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('proyectos')->insert(['id' => 1,'proyecto' => 'Bitcoin','ticker'=>'$BTC','descripcion'=>'Bitcoin es una criptomoneda descentralizada descrita originalmente en el Whitepaper de 2008 por una persona, o grupo de personas, con el alias de Satoshi Nakamoto. Se lanzó poco después, en enero de 2009.','website'=>'https://bitcoin.org/en/','link_analisis_kairos'=>'','twitter'=>'N/A','documentacion'=>'https://bitcoin.org/bitcoin.pdf','github'=>'https://github.com/bitcoin/bitcoin','discord'=>'N/A','ultima_ronda'=>'N/A','financiamiento'=>'0','inversionista1'=>'N/A','inversionista2'=>'N/A','inversionista3'=>'N/A' ]); 
        DB::table('proyectos')->insert(['id' => 2,'proyecto' => 'Ethereum','ticker'=>'$ETH','descripcion'=>'Ethereum es un sistema de cadena de bloques descentralizado y de código abierto que cuenta con su propia criptomoneda, Ether. Ethereum funciona como plataforma para muchas otras criptomonedas, así como para la ejecución de contratos inteligentes descentralizados.','website'=>'https://ethereum.org/es/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/ethereum','documentacion'=>'https://ethereum.org/en/whitepaper/','github'=>'https://github.com/ethereum','discord'=>'https://discord.com/invite/ethereum-org','ultima_ronda'=>'ICO','financiamiento'=>'18300.000','inversionista1'=>'N/A','inversionista2'=>'N/A','inversionista3'=>'N/A' ]); 
        DB::table('proyectos')->insert(['id' => 3,'proyecto' => 'Binance','ticker'=>'$BNB','descripcion'=>'Binance es la mayor bolsa de criptomonedas del mundo en volumen de operaciones diarias. El objetivo de Binance es situar las bolsas de criptomonedas a la vanguardia de la actividad financiera mundial. ','website'=>'https://www.binance.com/en','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/binance','documentacion'=>'N/A','github'=>'N/A','discord'=>'https://discord.com/invite/bnbchain','ultima_ronda'=>'Seed','financiamiento'=>'200000.000','inversionista1'=>'RRE Ventures','inversionista2'=>'Foundation Capital','inversionista3'=>'VanEck' ]); 
        DB::table('proyectos')->insert(['id' => 4,'proyecto' => 'Solana','ticker'=>'$SOL','descripcion'=>'Solana es un proyecto de código abierto altamente funcional que se basa en la naturaleza sin permisos de la tecnología blockchain para ofrecer soluciones financieras descentralizadas.','website'=>'https://solana.com/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/solana','documentacion'=>'https://solana.com/solana-whitepaper.pdf','github'=>'https://github.com/solana-labs','discord'=>'','ultima_ronda'=>'Indefinida','financiamiento'=>'314000.000','inversionista1'=>'A16z','inversionista2'=>'Polychain Capital','inversionista3'=>'Multicoin Capital' ]); 
        DB::table('proyectos')->insert(['id' => 5,'proyecto' => 'Ripple','ticker'=>'$XRP','descripcion'=>'Ripple es una tecnología descentralizada, sin permisos y de código abierto. Entre las ventajas del Ledger XRP se incluyen su bajo coste, velocidad, escalabilidad y atributos intrínsecamente ecológicos.','website'=>'https://xrpl.org/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/Ripple','documentacion'=>'https://arxiv.org/abs/1802.07242','github'=>'https://github.com/XRPLF/rippled','discord'=>'https://discord.com/invite/kBbATFA7PW','ultima_ronda'=>'Series B','financiamiento'=>'55000.000','inversionista1'=>'Standard Chartered','inversionista2'=>'Accenture Ventures','inversionista3'=>'SCB Digital Ventures' ]); 
        DB::table('proyectos')->insert(['id' => 6,'proyecto' => 'Dogecoin','ticker'=>'$DOGE','descripcion'=>'Dogecoin se basa en el popular meme de Internet «doge» y lleva un Shiba Inu en su logotipo. Los creadores de Dogecoin la concibieron como una criptomoneda divertida y desenfadada que, al estar basada en un meme canino, tendría un mayor atractivo más allá del público de Bitcoin.','website'=>'http://dogecoin.com/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/dogecoin','documentacion'=>'https://dogecoin.com/dogepedia/#documentation','github'=>'https://github.com/dogecoin/dogecoin','discord'=>'https://discord.com/invite/dogecoin','ultima_ronda'=>'N/A','financiamiento'=>'0','inversionista1'=>'N/A','inversionista2'=>'N/A','inversionista3'=>'N/A' ]); 
        DB::table('proyectos')->insert(['id' => 7,'proyecto' => 'Toncoin','ticker'=>'$TON','descripcion'=>'Toncoin es la criptomoneda nativa de la cadena de bloques descentralizada de capa 1, The Open Network. La blockchain TON es de código abierto y cuenta con el apoyo de muchos colaboradores de la red, incluida la Fundación TON, una organización sin ánimo de lucro con sede en Suiza.','website'=>'https://ton.org/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/ton_blockchain','documentacion'=>'https://ton.org/whitepaper.pdf','github'=>'https://github.com/ton-blockchain','discord'=>'N/A','ultima_ronda'=>'Indefinida','financiamiento'=>'0','inversionista1'=>'Pantera Capital','inversionista2'=>'N/A','inversionista3'=>'N/A' ]); 
        DB::table('proyectos')->insert(['id' => 8,'proyecto' => 'Cardano','ticker'=>'$ADA','descripcion'=>'Cardano es una plataforma blockchain de prueba de participación que afirma que su objetivo es permitir que «los agentes del cambio, los innovadores y los visionarios» provoquen un cambio global positivo.','website'=>'https://cardano.org/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/Cardano','documentacion'=>'https://docs.cardano.org/introduction','github'=>'https://github.com/input-output-hk/cardano-sl/','discord'=>'N/A','ultima_ronda'=>'ICO','financiamiento'=>'26770.000','inversionista1'=>'N/A','inversionista2'=>'N/A','inversionista3'=>'N/A' ]); 
        DB::table('proyectos')->insert(['id' => 9,'proyecto' => 'Shiba INU','ticker'=>'$SHIB','descripcion'=>'SHIB es una moneda descentralizada, dirigida por la comunidad y en manos de millones de personas en todo el mundo. Desde su creación a finales de 2020, el token SHIB basado en Ethereum ha crecido hasta convertirse en un fenómeno mundial, y ahora se acepta como forma de pago en cientos de lugares, ya sea directamente o a través de terceros intermediarios.','website'=>'https://shib.io/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/shibtoken','documentacion'=>'https://docs.shib.io/shibarium/','github'=>'','discord'=>'https://discord.com/invite/shibariumtech','ultima_ronda'=>'Indefinida','financiamiento'=>'12000.000','inversionista1'=>'Animoca Brands','inversionista2'=>'Shima Capital','inversionista3'=>'Morningstar Ventures' ]); 
        DB::table('proyectos')->insert(['id' => 10,'proyecto' => 'Avalanche','ticker'=>'$AVAX','descripcion'=>'Avalanche es una blockchain de capa uno que funciona como plataforma para aplicaciones descentralizadas y redes de blockchain personalizadas. Su objetivo es conseguir una mayor producción de transacciones, de hasta 6,500 transacciones por segundo, sin comprometer la escalabilidad.','website'=>'https://www.avalabs.org/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/avax','documentacion'=>'https://www.avalabs.org/whitepapers','github'=>'http://github.com/ava-labs','discord'=>'https://discord.com/invite/RwXY7P6','ultima_ronda'=>'Indefinida','financiamiento'=>'230000.000','inversionista1'=>'Polychain Capital','inversionista2'=>'Three Arrows Capital','inversionista3'=>'DragonFly Capital' ]); 
        DB::table('proyectos')->insert(['id' => 11,'proyecto' => 'Tron','ticker'=>'$TRX','descripcion'=>'TRON es un sistema operativo descentralizado basado en blockchain desarrollado por la Fundación Tron y lanzado en 2017. Originalmente, los tokens TRX eran tokens basados en ERC-20 desplegados en Ethereum, pero un año después se trasladaron a su propia red.','website'=>'https://tron.network/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/trondao','documentacion'=>'https://tron.network/static/doc/white_paper_v_2_0.pdf','github'=>'https://github.com/tronprotocol','discord'=>'https://discord.com/invite/hqKvyAM','ultima_ronda'=>'ICO','financiamiento'=>'76000.000','inversionista1'=>'N/A','inversionista2'=>'N/A','inversionista3'=>'N/A' ]); 
        DB::table('proyectos')->insert(['id' => 12,'proyecto' => 'Polkadot','ticker'=>'$DOT','descripcion'=>'Polkadot es un protocolo multicadena fragmentado de código abierto que conecta y protege una red de cadenas de bloques especializadas, facilitando la transferencia entre cadenas de cualquier tipo de datos o activos, no solo tokens, lo que permite que las cadenas de bloques sean interoperables entre sí. Polkadot se diseñó para sentar las bases de una Internet descentralizada de cadenas de bloques, también conocida como Web3.','website'=>'https://polkadot.network/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/Polkadot','documentacion'=>'https://polkadot.network/PolkaDotPaper.pdf','github'=>'https://github.com/paritytech/polkadot','discord'=>'https://discord.com/invite/polkadot','ultima_ronda'=>'Indefinida','financiamiento'=>'43000.000','inversionista1'=>'N/A','inversionista2'=>'N/A','inversionista3'=>'N/A' ]); 
        DB::table('proyectos')->insert(['id' => 13,'proyecto' => 'Bitcoin Cash','ticker'=>'$BCH','descripcion'=>'Bitcoin Cash es un sistema de dinero electrónico peer-to-peer que aspira a convertirse en dinero global sólido con pagos rápidos, micro comisiones, privacidad y bloques de mayor tamaño. Como criptomoneda descentralizada y sin permisos, Bitcoin Cash no requiere terceros de confianza y se creó como alternativa a Bitcoin.','website'=>'https://bch.info/','link_analisis_kairos'=>'','twitter'=>'N/A','documentacion'=>'https://gitlab.com/bitcoinunlimited','github'=>'https://github.com/bitcoincashorg/','discord'=>'','ultima_ronda'=>'N/A','financiamiento'=>'0','inversionista1'=>'N/A','inversionista2'=>'N/A','inversionista3'=>'N/A' ]); 
        DB::table('proyectos')->insert(['id' => 14,'proyecto' => 'Chainlink','ticker'=>'$LINK','descripcion'=>'Chainlink es una capa de abstracción de blockchain que permite contratos inteligentes conectados universalmente. A través de una red de oráculos descentralizada, Chainlink permite a las cadenas de bloques interactuar de forma segura con fuentes de datos externas, eventos y métodos de pago, proporcionando la información crítica fuera de la cadena que necesitan los contratos inteligentes complejos para convertirse en la forma dominante de acuerdo digital.','website'=>'https://chain.link/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/chainlink','documentacion'=>'https://research.chain.link/whitepaper-v2.pdf','github'=>'https://github.com/smartcontractkit/chainlink','discord'=>'https://discord.com/invite/chainlink','ultima_ronda'=>'ICO','financiamiento'=>'3000.000','inversionista1'=>'N/A','inversionista2'=>'N/A','inversionista3'=>'N/A' ]); 
        DB::table('proyectos')->insert(['id' => 15,'proyecto' => 'NEAR Protocol','ticker'=>'$NEAR','descripcion'=>'El protocolo NEAR es una cadena de bloques de una sola capa diseñada como una plataforma de computación en nube gestionada por la comunidad y que elimina algunas de las limitaciones que han venido lastrando las cadenas de bloques de la competencia, como la baja velocidad de las transacciones, el bajo rendimiento y la escasa interoperabilidad.','website'=>'https://near.org/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/nearprotocol','documentacion'=>'https://near.org/papers/the-official-near-white-paper/','github'=>'https://github.com/near','discord'=>'https://discord.com/invite/zfhfRpaM4m','ultima_ronda'=>'Indefinida','financiamiento'=>'350000.000','inversionista1'=>'Tiger Global Management','inversionista2'=>'DragonFly Capital','inversionista3'=>'Hashed Fund' ]); 
        DB::table('proyectos')->insert(['id' => 16,'proyecto' => 'Polygon','ticker'=>'$MATIC','descripcion'=>'Polygon es la primera plataforma bien estructurada y fácil de usar para el escalado de Ethereum y el desarrollo de infraestructuras. Su componente principal es Polygon SDK, un marco modular y flexible que permite crear múltiples tipos de aplicaciones.','website'=>'https://polygon.technology/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/0xPolygon','documentacion'=>'https://polygon.technology/papers/pol-whitepaper','github'=>'https://github.com/maticnetwork','discord'=>'https://discord.com/invite/0xPolygon','ultima_ronda'=>'Indefinida','financiamiento'=>'450000.000','inversionista1'=>'Peak XV Partners','inversionista2'=>'The Spartan Club','inversionista3'=>'DragonFly Capital' ]); 
        DB::table('proyectos')->insert(['id' => 17,'proyecto' => 'Litecoin','ticker'=>'$LTC','descripcion'=>'Litecoin es una criptomoneda diseñada para proporcionar pagos rápidos, seguros y de bajo coste aprovechando las propiedades únicas de la tecnología blockchain. La criptomoneda se creó basándose en el protocolo de Bitcoin, pero difiere en cuanto al algoritmo hash utilizado, el hard cap, los tiempos de transacción de los bloques y algunos otros factores.','website'=>'https://www.litecoin.net/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/Litecoin','documentacion'=>'N/A','github'=>'https://github.com/litecoin-project/litecoin','discord'=>'N/A','ultima_ronda'=>'N/A','financiamiento'=>'0','inversionista1'=>'N/A','inversionista2'=>'N/A','inversionista3'=>'N/A' ]); 
        DB::table('proyectos')->insert(['id' => 18,'proyecto' => 'Internet Computer Protocol','ticker'=>'$ICP','descripcion'=>'Internet Computer Protocol incorpora un replanteamiento radical del diseño de blockchain, impulsado por innovaciones en criptografía. Proporciona el primer «ordenador mundial» blockchain que puede utilizarse para construir casi cualquier sistema o servicio en línea, incluidos los exigentes medios sociales de la web, sin necesidad de TI tradicionales como los servicios de computación en nube. Como tal, puede permitir la descentralización completa de extremo a extremo.','website'=>'https://dfinity.org/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/dfinity','documentacion'=>'https://internetcomputer.org/docs/current/references/ic-interface-spec','github'=>'https://github.com/dfinity','discord'=>'N/A','ultima_ronda'=>'Indefinida','financiamiento'=>'102000.000','inversionista1'=>'A16z','inversionista2'=>'Polychain Capital','inversionista3'=>'Multicoin Capital' ]); 
        DB::table('proyectos')->insert(['id' => 19,'proyecto' => 'UNU SED LEO','ticker'=>'$LEO','descripcion'=>'','website'=>'https://www.bitfinex.com/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/bitfinex','documentacion'=>'https://www.bitfinex.com/wp-2019-05.pdf','github'=>'N/A','discord'=>'https://discord.com/invite/bitfinex','ultima_ronda'=>'Private Token Sale','financiamiento'=>'1000000.000','inversionista1'=>'N/A','inversionista2'=>'N/A','inversionista3'=>'N/A' ]); 
        DB::table('proyectos')->insert(['id' => 20,'proyecto' => 'Uniswap','ticker'=>'$UNI','descripcion'=>'Uniswap es un popular protocolo de comercio descentralizado, conocido por su papel a la hora de facilitar el comercio automatizado de tokens financieros descentralizados. El objetivo de Uniswap es mantener la negociación de tokens automatizada y completamente abierta a cualquiera que posea tokens, al tiempo que mejora la eficiencia de la negociación frente a la de las bolsas tradicionales.','website'=>'https://uniswap.org/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/uniswap/','documentacion'=>'https://uniswap.org/whitepaper-v3.pdf','github'=>'https://github.com/Uniswap','discord'=>'https://discord.com/invite/XErMcTq','ultima_ronda'=>'Serie B','financiamiento'=>'165000.000','inversionista1'=>'Polychain Capital','inversionista2'=>'A16z','inversionista3'=>'Paradigm' ]); 
        DB::table('proyectos')->insert(['id' => 21,'proyecto' => 'Alt Layer','ticker'=>'$ALT','descripcion'=>'AltLayer es un protocolo abierto y descentralizado para rollups. AltLayer reúne una idea novedosa de Rollups Restaked que toma rollups ( generado desde cualquier rollup stack como OP Stack, Arbitrum Orbit, Polygon CDK, ZK Stack, etc.) y les proporciona una mayor seguridad, descentralización, interoperabilidad y cripto-económica rápida finalidad aprovechando mecanismo restaking.','website'=>'https://altlayer.io/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/Alt_Layer','documentacion'=>'https://docs.altlayer.io/altlayer-documentation/welcome/overview','github'=>'https://github.com/alt-research','discord'=>'https://discord.com/invite/altlayer','ultima_ronda'=>'Estrategica','financiamiento'=>'14400.000','inversionista1'=>'Polychain Capital','inversionista2'=>'Hack VC','inversionista3'=>'N/A' ]); 
        DB::table('proyectos')->insert(['id' => 22,'proyecto' => 'Peaq','ticker'=>'$PEAQ','descripcion'=>'Peaq es la cadena de bloques para aplicaciones del mundo real. La blockchain de capa 1 de peaq permite a cualquiera crear aplicaciones descentralizadas (dApps) y redes de infraestructura física descentralizada (DePINs) para compartir coche, mapear calles, acceder a la web y mucho más, creando valor en el mundo real como parte de la Economía de las Cosas.','website'=>'https://www.peaq.network/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/peaqnetwork','documentacion'=>'https://docs.peaq.network/docs/quick-start/what-is-peaq/','github'=>'https://github.com/peaqnetwork','discord'=>'https://discord.com/invite/XhJwuFKAAD','ultima_ronda'=>'Indefinida','financiamiento'=>'6000.000','inversionista1'=>'Fundamental Labs','inversionista2'=>'HashKey Capital','inversionista3'=>'GSR' ]); 
        DB::table('proyectos')->insert(['id' => 23,'proyecto' => 'Sei','ticker'=>'$SEI','descripcion'=>'Sui es la primera plataforma de blockchain y contratos inteligentes de nivel 1 diseñada para que la propiedad de activos digitales sea rápida, privada, segura y accesible.','website'=>'https://www.seinetwork.io/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/SeiNetwork','documentacion'=>'https://docs.seinetwork.io/introduction/overview','github'=>'https://github.com/sei-protocol/sei-chain','discord'=>'https://discord.com/invite/sei','ultima_ronda'=>'Indefinida','financiamiento'=>'30000.000','inversionista1'=>'Multicoin Capital','inversionista2'=>'Hypersphere Ventures','inversionista3'=>'OKX Ventures' ]); 
        DB::table('proyectos')->insert(['id' => 24,'proyecto' => 'Injective','ticker'=>'$INJ','descripcion'=>'Injective es una cadena de bloques creada para las finanzas. Se trata de una cadena de bloques abierta, interoperable y de capa uno que impulsa las aplicaciones DeFi de próxima generación, incluidos los intercambios descentralizados al contado y de derivados, los mercados de predicción, los protocolos de préstamo y mucho más. Injective proporciona de forma única potentes primitivas de infraestructura financiera básica que las aplicaciones pueden aprovechar, incluido un libro de órdenes en cadena totalmente descentralizado y resistente a MEV.','website'=>'https://injective.com/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/injective','documentacion'=>'https://docs.injective.network/','github'=>'https://github.com/InjectiveLabs','discord'=>'https://discord.com/invite/NK4qdbv','ultima_ronda'=>'Indefinida','financiamiento'=>'40000.000','inversionista1'=>'Jump Crypto ','inversionista2'=>'Bh Capital','inversionista3'=>'N/A' ]); 
        DB::table('proyectos')->insert(['id' => 25,'proyecto' => 'Polimec','ticker'=>'$PLMC','descripcion'=>'Polimec proporciona un marco automatizado para que los proyectos recauden fondos dentro de una comunidad amplia y diversa con un acceso transparente y justo para todos. El protocolo proporciona acceso a la recaudación de fondos y gestiona la emisión, distribución y conversión de tokens a mainnet.','website'=>'https://www.polimec.org/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/PolimecProtocol','documentacion'=>'https://hub.polimec.org/','github'=>'https://github.com/Polimec','discord'=>'https://discord.com/invite/4CZh8HNVuT','ultima_ronda'=>'N/A','financiamiento'=>'0','inversionista1'=>'N/A','inversionista2'=>'N/A','inversionista3'=>'N/A' ]); 
        DB::table('proyectos')->insert(['id' => 26,'proyecto' => 'Push Protocol','ticker'=>'$PUSH','descripcion'=>'Push Protocol, es el protocolo de comunicación de web3. Push protocol permite notificaciones y mensajería a través de la cadena para dapps, billeteras y servicios vinculados a direcciones de billetera de una manera abierta, sin gas y agnóstica a la plataforma. La capa de comunicación abierta permite a cualquier monedero criptográfico / frontend acceder a la red y transmitir la comunicación.','website'=>'https://push.org/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/pushprotocol','documentacion'=>'https://push.org/docs/','github'=>'https://github.com/push-protocol/','discord'=>'https://discord.com/invite/pushprotocol','ultima_ronda'=>'Serie A','financiamiento'=>'10100.000','inversionista1'=>'Jump Crypto','inversionista2'=>'ParaFi Capital','inversionista3'=>'Tiger Global Management' ]); 
        DB::table('proyectos')->insert(['id' => 27,'proyecto' => 'IPOR','ticker'=>'$IPOR','descripcion'=>'IPOR es el primer intento en DeFi de establecer una curva de rendimiento que represente el coste medio de los préstamos en DeFi con información publicada en la cadena por los mayores protocolos del mercado de crédito en DeFi: Aave, Compound, DSR de DAI y Lido.','website'=>'https://www.ipor.io/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/ipor_io','documentacion'=>'https://docs.ipor.io/readme','github'=>'https://github.com/IPOR-Labs','discord'=>'https://discord.com/invite/bSKzq6UMJ3','ultima_ronda'=>'Seed','financiamiento'=>'5550.000','inversionista1'=>'Arrignton XRP Capital','inversionista2'=>'CMT Digital','inversionista3'=>'C2 Ventures' ]); 
        DB::table('proyectos')->insert(['id' => 28,'proyecto' => 'Landex','ticker'=>'$LNDX','descripcion'=>'LandX Finance es un protocolo de bóvedas de productos básicos perpetuos, que proporciona y permite de manera efectiva a los agricultores en tiempo real interactuar de manera fácil y productiva con los inversores que necesitan adquirir acciones de cultivos mediante el manejo de tokens líquidos.','website'=>'https://landx.fi/','link_analisis_kairos'=>'','twitter'=>'https://twitter.com/landxfinance','documentacion'=>'https://landx.gitbook.io/landx','github'=>'','discord'=>'N/A','ultima_ronda'=>'Private Token Sale','financiamiento'=>'915','inversionista1'=>'N/A','inversionista2'=>'N/A','inversionista3'=>'N/A' ]); 
    }
}
